#Respuestas por defecto
# -*- coding: latin-1 -*-
opciones = {
    "users": {"Pablo Marinozi","Facundo Bromberg","Diego Sebasti�n P�rez","Carlos Ariel D�az","Wenceslao Villegas","Juan Manuel L�pez Correa"},
    "inclusion_criteria": ("El estudio utiliza alg�n proceso de extracci�n de informaci�n automatizado sobre im�genes de cualquier regi�n del espectro electromagn�tico en alguna de sus etapas.",
                           "El estudio se enfoca en la medici�n de variables de inter�s vit�cola indistintamente de la ubicaci�n geogr�fica y el sistema de conducci�n de los vi�edos y del varietal y prop�sito de comercializaci�n de las uvas."),
    "exclusion_criteria": ("El estudio utiliza como entrada im�genes satelitales.",
                            "El algoritmo opera sobre informaci�n electromagn�tica que no viene en forma de imagen (enti�ndase representaci�n visual bidimensional a partir de una matriz num�rica) ",
                            "El paper est� orientado a automatismo de la gesti�n, no a medici�n de variables.",
                            "El estudio no est� escrito en Ingl�s.",
                            "La publicaci�n del estudio no se someti� a un proceso de revisi�n por pares."),
    "dataset_format_list" : {"Fotograf��as Aisladas", "Fotogramas de videos"},
    "viticultural_objects_list" : {"Bayas (Racimos)", "Bayas (Granos)", "Hojas (Individuales)", "Hojas (Canopia)",
                                 "Yemas", "Tronco"},
    "data_capture_conditions_list" : {"Condiciones naturales de campo", "Condiciones controladas en el campo",
                              "Condiciones controladas en el laboratorio"}, 
    "electromagnetic_spectrum_list" : {"Espectro Visible", "Infrarrojo", "Multiespectral", "Hiperespectral"},
    "camera_types_list" : {"Monocular", "Stereo", "Profundidad"},
    "visual_tasks_list" : {
        "Segmentaci�n 2D de objetos de inter�s.",
        "Detecci�n 2D de objetos de inter�s (bounding box)",
        "Detecci�n 2D de objetos de inter�s (centro de masa)",
        "Detecci�n 2D de objetos de inter�s (m�scara del objeto 2D)",
        "Detecci�n 3D de objetos de inter�s (bounding box)",
        "Detecci�n 3D de objetos de inter�s (centro de masa)",
        "Detecci�n 3D de objetos de inter�s (m�scara del objeto 3D)",
        "Reconstrucci�n 3D de objetos de inter�s.",
        "Identificaci�n/Diferenciaci�n 2D/3D de instancias de objeto de inter�s.",
        "Tracking de objetos de inter�s"},
    "visual_features_types": {"Handcrafted", "Latent", "Deep"},
    "visual_features_handcrafted_list" : {
        "M�scaras de Textura de Laws",
        "Filtros de Gabor",
        "SGF (Steerable Gaussian Filter)",
        "Histogramas de color",
        "CCV (Color Coherence Vector)",
        "Histogramas de Momentos de Color",
        "CC (Color Correlogram)",
        "GCM (Gray-level Co-occurrence Matrix)",
        "Contexto de Forma (Shape Context)",
        "Momentos Geom�tricos",
        "HOG (Histogram of Oriented Gradients)",
        "SIFT (Scale-Invariant Feature Transform)",
        "SURF (Speeded-Up Robust Features)",
        "ORB (Oriented FAST and rotated BRIEF)"},
    "visual_features_latent_list" : {
        "PCA (Principal Component Analysis)",
        "Kernel PCA (Kernel Principal Component Analysis)",
        "MDS (Multidimensional Scaling",
        "Isomap",
        "Laplacian Eigenmaps"},
    "visual_features_deep_list" : {
        "AlexNet",
        "VGG group",
        "LeNet",
        "GoogleNet",
        "Inception"},
    "algorithms_list" : {"SVM (Support Vector Machines)", "Multilayer Perceptron"},
    "viticultural_variable_list" : {
        "Flower number",
        "Berry maturity",
        "Berry number",
        "Berry weight" ,
        "Berry size",
        "Berry volume",
        "Cluster compactness (density)",
        "Cluster morphology (length, width, size, elongation)",
        "Cluster volume",
        "Cluster number",
        "Cluster weight",
        "Yield",
        "Leaf Area"},
    "viticultural_aspects_list" : {
        "Informaci�n cuantitativa de la producci�n",
        "Calidad de la producci�n",
        "Estado general del vi�edo"},
    "research_goal_list" : {
        "Disminuir costos en procesos productivos.",
        "Reducir la laboriosidad de las tareas manuales llevadas adelante por el personal.",
        "Posibilitar las mediciones actuales en escala masiva/mayor granularidad espacio-temporal.",
        "Posibilitar la medici�n de variables m�s complejas/sutiles que las actuales."},
    "practical_contibution_list" : {
        "Producto terminado de c�digo abierto.",
        "Producto terminado privativo.",
        "Implementaci�n de c�digo abierto de los modelos de CV",
        "Ninguna de las anteriores."},
    "varietal_list" : {
        "Malbec",
        "Cabernet Sauvignon",
        "Merlot",
        "Chardonnay",
        "Syrah",
        "Bonarda",
        "Tempranillo"},
    "irrigation_conduction_list" : {
        "Espaldero",
        "Parra"}
}